services:
  local_postgres:
    image: postgres:15-alpine
    container_name: local_postgres
    environment:
      - POSTGRES_DB=philosophy_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

volumes:
  local_postgres_data:
