sonar.projectKey=root_python-ai-service_ae959733-5c9d-4133-ae3e-740f4b07407e
sonar.projectName=AI
sonar.host.url=https://sonar.delez-repo.ru
sonar.token=$SONAR_TOKEN

sonar.sources=app,scripts
sonar.tests=tests
sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml

sonar.coverage.lineThreshold=70
sonar.coverage.branchThreshold=60

sonar.exclusions=venv/**,tests/**,migrations/**,docs/**,__pycache__/**,common/**,scripts/**